#!/bin/bash
# Converts a STOPGAP motive list (motl) to an AV3 text file which can be read by Chimera "Place Object" plugin. 
# Based on MATLAB script sg_motl_stopgap_to_av3 from sg_toolbox
# 
# RDR 24/11/2020

motlfile=$1
av3file=$2

matlab -batch "sg_motl_stopgap_to_av3('$motlfile','$av3file')"
