#!/bin/bash
# Converts a STOPGAP motive list (motl) to a text file with the points. This text file can later be read by IMOD e.g. with point2model.

awk '($2 == 9) {print $3, $6+$10, $7+$11, $8+$12}' $1 > $2
