#!/usr/bin/env bash
set -e              # Crash on error
set -o nounset      # Crash on unset variables
# WW 12-2018
# RDR 11-2020

# Read config file. Can be given as an argument or read from the current directory.

# Check if we are on sciCORE cluster:
if [ `hostname | grep bc2.ch | echo $?` -eq 0 ]; then 
    ml purge
    ml load MCR/9.0
    ml load OpenMPI/4.1.1-GCC-10.3.0
fi

cfgfile=sg_subtomo.cfg
if [ $# -eq 0 ]; then
    source ${cfgfile}
else
    source "$1"
fi
rootdir=`pwd`/  # Root subtomogram averaging directory (automatically defined as the directory from which the script is called)



################################################################################################################################################################
echo "Preparing for subtomogram extraction..."

##### PATHS #####
extract="${STOPGAPHOME}/bin/stopgap_extract_mpi.sh"

##### CHECK CHECK #####
# Check root directory
cd $rootdir

# Clear comm_dir
rm -f ${comm_dir-comm/}*

# Remove old parameter file
rm -rf extract_param.txt

# Remove old submission files
rm -rf submit_extract

##### WRITE PARAMETER FILE #####
echo "rootdir=${rootdir}" > extract_param.txt
echo "motl_name=${motl_name_extract}" >> extract_param.txt
echo "tomo_dir=${tomo_dir}" >> extract_param.txt
echo "tomo_digits=${tomo_digits}" >> extract_param.txt
echo "subtomo_name=${subtomo_name}" >> extract_param.txt
echo "subtomo_digits=${subtomo_digits}" >> extract_param.txt
echo "boxsize=${boxsize}" >> extract_param.txt
echo "pixelsize=${pixelsize}" >> extract_param.txt
echo "n_cores=${n_cores}" >> extract_param.txt

echo "     (~‾▿‾)~ BEGIN EXTRACTION ~(‾▿‾~)"

eval "mpirun -np  $n_cores $extract $rootdir extract_param.txt"

exit








