#! /usr/bin/env bash
set -e              # Crash on error
set -o nounset      # Crash on unset variables

## run_stopgap.sh
# A script for performing subtomogram averaging using 'stopgap'.
# This script first generates a submission file and then launches 
# 'stopgap_watcher', a MATLAB executable that manages the flow of parallel 
# stopgap averging jobs.
#
# Stopgap uses a special .star file to define the subtomogram averaging 
# parameters. These .star files can be generated using 'stopgap_job_parser.sh'.
#
# WW 06-2018
# RDR 11-2020

# Read config file. Can be given as an argument or read from the current directory.

# Check if we are on sciCORE cluster:
if [ `hostname | grep bc2.ch | echo $?` -eq 0 ]; then 
    ml purge
    ml load MCR/9.0
    ml load OpenMPI/4.1.1-GCC-10.3.0
fi

cfgfile=sg_run.cfg
if [ $# -eq 0 ]; then
    source ${cfgfile}
else
    source "$1"
fi
rootdir=`pwd`/  # Root subtomogram averaging directory (automatically defined as the directory from which the script is called)



################################################################################################################################################################
##### SUBTOMOGRAM AVERAGING WORKFLOW                                                                                                       ie. the nasty bits...
################################################################################################################################################################

# Path to MATLAB executables
watcher="${STOPGAPHOME}/bin/stopgap_watcher.sh"
# subtomo="${STOPGAPHOME}/bin/stopgap_mpi_slurm.sh"
subtomo="${STOPGAPHOME}/bin/stopgap_array_slurm.sh"


# Remove previous submission script
rm -f submit_stopgap

if [ "${run_type}" = "local" ]; then
    echo "Running stopgap locally..."


    # Local submit command
    submit_cmd="mpiexec -np ${n_cores} ${subtomo} ${rootdir} ${paramfilename} ${n_cores}  2> ${rootdir}/error_stopgap 1> ${rootdir}/log_stopgap &"
    # echo ${submit_cmd}


elif [ "${run_type}" = "sge" ]; then
    echo "Preparing to run stopgap on SGE-cluster..."

    # Write submission script
    echo "#! /usr/bin/env bash" > submit_stopgap
    echo "#$ -pe openmpi ${n_cores}" >> submit_stopgap             # Number of cores
    echo "#$ -l h_vmem=${mem_limit}" >> submit_stopgap             # Memory limit
    echo "#$ -l h_rt=${wall_time}" >> submit_stopgap               # Wall time
    echo "#$ -q ${queue}" >> submit_stopgap                        # Averaging queue
    echo "#$ -e ${rootdir}/error_stopgap" >> submit_stopgap        # Error file
    echo "#$ -o ${rootdir}/log_stopgap" >> submit_stopgap          # Log file
    echo "#$ -S /bin/bash" >> submit_stopgap                       # Submission environment
    echo "source ~/.bashrc" >> submit_stopgap                      # Get proper envionment; i.e. modules
    echo "mpiexec -np ${n_cores} ${subtomo} ${rootdir} ${paramfilename} ${n_cores}" >> submit_stopgap
    echo "exit" >> submit_stopgap
    
    # Make executable
    chmod +x submit_stopgap
    
    # Submission command
    submit_cmd="qsub submit_stopgap"

elif [ "${run_type}" = "slurm" ]; then
    echo "Preparing to run stopgap on slurm-cluster..."

    # Convert seconds to minutes, taking the ceiling
    wall_time=$(((($wall_time-1)/60)+1))

    # Write submission script
    echo "#! /usr/bin/env bash" > submit_stopgap
    echo "#SBATCH -D ${rootdir}" >> submit_stopgap
    echo "#SBATCH -e error_stopgap.job%j" >> submit_stopgap
    echo "#SBATCH -o log_stopgap.job%j" >> submit_stopgap
    echo "#SBATCH -J stopgap_subtomo" >> submit_stopgap
    echo "#SBATCH --partition=${queue} " >> submit_stopgap
    echo "#SBATCH --qos=${qos}" >> submit_stopgap
    echo "#SBATCH --ntasks=${n_cores}" >> submit_stopgap
    echo "#SBATCH --mem-per-cpu=${mem_limit}" >> submit_stopgap
    echo "#SBATCH --time=${wall_time}" >> submit_stopgap
    echo "" >> submit_stopgap
    echo "ml purge" >> submit_stopgap
    echo "ml load MCR/9.0" >> submit_stopgap
    echo "ml load OpenMPI/4.1.1-GCC-10.3.0" >> submit_stopgap
    echo "srun ${subtomo} ${rootdir} ${paramfilename} ${n_cores}" >> submit_stopgap

    # Make executable
    chmod +x submit_stopgap
    
    # Submission command
    submit_cmd="sbatch submit_stopgap"

elif [ "${run_type}" = "slurm_array" ]; then
    echo "Preparing to run stopgap on slurm-cluster..."

    # Convert seconds to minutes, taking the ceiling
    wall_time=$(((($wall_time-1)/60)+1))

    if [ ${mem_limit_array_task}x == "x" ]; then
        mem_limit_array_task="2G" # Set a safe default
    fi

    # We split the submission scripts in two: one for the manager, which requires a lot of memory, and one for the subtasks, which typically require less memory.
    # Write array tasks submission script
    echo "#! /usr/bin/env bash" > submit_stopgap_array_task
    echo "#SBATCH -D ${rootdir}" >> submit_stopgap_array_task
    echo "#SBATCH -e error_stopgap_array_tasks.job%A" >> submit_stopgap_array_task
    echo "#SBATCH -o log_stopgap_array_tasks.job%A" >> submit_stopgap_array_task
    echo "#SBATCH --open-mode=append" >> submit_stopgap_array_task
    echo "#SBATCH -J stopgap" >> submit_stopgap_array_task
    echo "#SBATCH --partition=${queue} " >> submit_stopgap_array_task
    echo "#SBATCH --qos=${qos}" >> submit_stopgap_array_task
    # echo "#SBATCH --ntasks=${n_cores}" >> submit_stopgap_array_task
    # echo "#SBATCH --mem-per-cpu=${mem_limit}" >> submit_stopgap_array_task
    echo "#SBATCH --mem=${mem_limit_array_task}" >> submit_stopgap_array_task
    echo "#SBATCH --array=2-${n_cores}" >> submit_stopgap_array_task
    echo "#SBATCH --time=${wall_time}" >> submit_stopgap_array_task
    echo "" >> submit_stopgap_array_task
    echo "module purge" >> submit_stopgap_array_task
    echo "module load MCR/9.0" >> submit_stopgap_array_task
    echo "module load OpenMPI/4.1.1-GCC-10.3.0" >> submit_stopgap_array_task
    # echo "srun ${subtomo} ${rootdir} ${paramfilename} ${n_cores}" >> submit_stopgap_array_task
    echo "${subtomo} ${rootdir} ${paramfilename} ${n_cores}" >> submit_stopgap_array_task

    # Make executable
    chmod +x submit_stopgap_array_task

    # Write array manager submission script
    echo "#! /usr/bin/env bash" > submit_stopgap_array_manager
    echo "#SBATCH -D ${rootdir}" >> submit_stopgap_array_manager
    echo "#SBATCH -e error_stopgap_array_manager.job%A" >> submit_stopgap_array_manager
    echo "#SBATCH -o log_stopgap_array_manager.job%A" >> submit_stopgap_array_manager
    echo "#SBATCH --open-mode=append" >> submit_stopgap_array_manager
    echo "#SBATCH -J stopgap" >> submit_stopgap_array_manager
    echo "#SBATCH --partition=${queue} " >> submit_stopgap_array_manager
    echo "#SBATCH --qos=${qos}" >> submit_stopgap_array_manager
    # echo "#SBATCH --ntasks=${n_cores}" >> submit_stopgap_array_manager
    # echo "#SBATCH --mem-per-cpu=${mem_limit}" >> submit_stopgap_array_manager
    echo "#SBATCH --mem=${mem_limit}" >> submit_stopgap_array_manager
    echo "#SBATCH --array=1-1" >> submit_stopgap_array_manager
    echo "#SBATCH --time=${wall_time}" >> submit_stopgap_array_manager
    echo "" >> submit_stopgap_array_manager
    echo "module purge" >> submit_stopgap_array_manager
    echo "module load MCR/9.0" >> submit_stopgap_array_manager
    echo "module load OpenMPI/4.1.1-GCC-10.3.0" >> submit_stopgap_array_manager
    # echo "srun ${subtomo} ${rootdir} ${paramfilename} ${n_cores}" >> submit_stopgap_array_manager
    echo "${subtomo} ${rootdir} ${paramfilename} ${n_cores}" >> submit_stopgap_array_manager

    # Make executable
    chmod +x submit_stopgap_array_manager
    
    # Submission command
    submit_cmd="sbatch submit_stopgap_array_manager; sbatch submit_stopgap_array_task"

else
    echo 'ACHTUNG!!! Invalid run_type!!!'
    echo 'Only supported run_types are "local", "sge", "slurm" and "slurm_array"!!!'
    exit 1
fi



# Run watcher
eval "${watcher} ${rootdir} ${paramfilename} ${n_cores} '${submit_cmd}'"
rm -f submit_stopgap

exit




