#!/bin/bash

# Script to convert a STOPGAP motive list STAR file to bild format for plotting angular distribution
# Based on star2bild.py from PyEM: https://github.com/asarnow/pyem/

# module purge
module load PYEM

input=$1
output=$2
apix=$3
boxsize=$4

echo "data_particles" > tmp.star
echo "" >>tmp.star
echo "loop_" >> tmp.star
echo "_rlnAngleRot #1" >> tmp.star
echo "_rlnAnglePsi #2" >> tmp.star
echo "_rlnAngleTilt #3" >> tmp.star

awk '{ if (NF > 1) print $13, $14, $15}' $1 >> tmp.star

python `which star2bild.py` tmp.star $2 --apix $3 --boxsize $4

\rm tmp.star
